### ISSUE TITLE
Visiting admin panel shows nothing?

### ISSUE THREAD

**Issue by ismyhc** [bitclout/run#18]
Syncing now and when visiting admin section I see no stats. Is this normal?

**Comment by chafreaky** [comment]
Make sure you logged in with the same key you specified as an admin key in dev.env and hard refresh (or clear cache), should do the trick.

**Comment by ismyhc** [comment]
Hmmm according to the dev.env comment if ADMIN_PUBLIC_KEYS is blank anyone should be able to see.

# admin_public_keys is list of public keys delimited by commas or new-lines
# which gives users access to the admin panel. If no keys are specified
# anyone can access the admin panel. You can add a space and a comment after
# every public key and leave a note about who the public key belongs to.


At any rate, I added my public key from my profile and doing hard refresh on browser still shows nothing on admin panel. Do i need to start resyncing from beginning?

**Comment by chafreaky** [comment]
You don't need to restart syncing but you need to bring your docker down and then back up, a simple restart is not enough.

e.g.
`docker-compose -f ${FILE} down`
`docker-compose -f ${FILE} up`

**Comment by ismyhc** [comment]
No dice :(

Even tried restarting my machine. On ubuntu 20.04
![Screenshot from 2021-04-23 18-34-49](https://user-images.githubusercontent.com/840551/115936311-e58e7180-a462-11eb-94e8-3f4c1605bf29.png)
![Screenshot from 2021-04-23 18-36-19](https://user-images.githubusercontent.com/840551/115936313-e58e7180-a462-11eb-967f-ef9089058206.png)

**Comment by chafreaky** [comment]
There is a MAX_BLOCK_TEMPLATES_TO_CACHE var in dev.env that you need to edit and make sure it is above 0. Bring docker down and back up and it should be working!

**Comment by chafreaky** [comment]
@maebeam is this something that we should add to the readme tips or am I completely off?

**Comment by ismyhc** [comment]
Hmmmm. Tried that as well. set MAX_BLOCK_TEMPLATES_TO_CACHE=1

Still the same issue. Admin page has no stats.

Also, getting an error when I try:
```
~/bclout/run$ docker-compose -f docker-compose.dev.yml down --volumes
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
```

**Comment by ismyhc** [comment]
Ps, figured out the error when trying to bring down the docker container. Just needed to run it with sudo. Now, gonna try and get this thing back up and running

**Comment by pangia** [comment]
I'm still getting this error in the console. did you resolve it @ismyhc ?

**Comment by UnknownNFT** [comment]
I'm also experiencing a white screen when attempting to view the admin panel
![image](https://user-images.githubusercontent.com/83103574/115971524-cdb7fb80-a4fd-11eb-8b35-59fb51666250.png)

**Comment by Sigil-Wen** [comment]
Also getting an error :(

**Comment by maebeam** [comment]
Hey everyone, thanks for your patience. I'll look at this tomorrow

**Comment by jimchimino** [comment]
good afternoon. or more detailed instructions for work. I installed Docker, and then what? where to copy these files and where to find the RUN button?

**Comment by maebeam** [comment]
I believe this is fixed. Please reopen if you're still experiencing this issue.
